In [34]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler

In [3]:
df = pd.read_csv("/kaggle/input/datasets/pradeepisawasan/dirty-iris-dataset/dirty_iris.csv")

In [4]:
df.shape

(150, 5)

In [6]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,NaN,0.2,setosa
2,4.7,3.2,NaN,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [9]:
df.isnull().any()

sepal length (cm)     True
sepal width (cm)      True
petal length (cm)     True
petal width (cm)      True
species              False
dtype: bool

In [11]:
df.isnull().sum()

sepal length (cm)    23
sepal width (cm)     15
petal length (cm)    18
petal width (cm)     16
species               0
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [13]:
num_cols = df.select_dtypes(include = np.number).columns

In [14]:
num_cols

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [15]:
for col in num_cols:
    df[col] = df[col].fillna(df[col].mean())

In [16]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.400000,0.2,setosa
1,4.9,3.0,3.737879,0.2,setosa
2,4.7,3.2,3.737879,0.2,setosa
3,4.6,3.1,1.500000,0.2,setosa
4,5.0,3.6,1.400000,0.2,setosa

In [19]:
df.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [22]:
label_encoder = LabelEncoder()

df['species'] =  label_encoder.fit_transform(df["species"])

In [23]:
label_encoder.classes_

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [24]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.400000,0.2,0
1,4.9,3.0,3.737879,0.2,0
2,4.7,3.2,3.737879,0.2,0
3,4.6,3.1,1.500000,0.2,0
4,5.0,3.6,1.400000,0.2,0

In [25]:
X = df.drop("species",axis = 1)
y = df["species"]

In [26]:
scaler = StandardScaler()

In [27]:
X = scaler.fit_transform(X)

In [28]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 2026)

In [29]:
X_train.shape

(120, 4)

In [30]:
X_test.shape

(30, 4)

In [31]:
y_train.shape

(120,)

In [32]:
y_test.shape

(30,)

In [35]:
df.to_csv("cleaned_dirty_iris.csv",index=False)